name: Build Docker Images

on:
  workflow_dispatch:
  
permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  build-api:
    name: Build API docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/api/Dockerfile
          push: true
          tags: |
            ghcr.io/wemem/omnivore-api:${{ github.sha }}
            ghcr.io/wemem/omnivore-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-content-fetch:
    name: Build Content Fetch docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push Content Fetch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/content-fetch/Dockerfile
          push: true
          tags: |
            ghcr.io/wemem/omnivore-content-fetch:${{ github.sha }}
            ghcr.io/wemem/omnivore-content-fetch:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
