name: Build Docker Images

on:
  workflow_dispatch:
  
permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Login to GitHub container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the backend docker image
        run: |
          docker build . --file packages/api/Dockerfile --tag "ghcr.io/wemem/omnivore-api:${GITHUB_SHA}" --tag ghcr.io/wemem/omnivore-api:latest
          docker push ghcr.io/wemem/omnivore-api:${GITHUB_SHA}
      - name: Build the content-fetch docker image
        run: |
          docker build --file packages/content-fetch/Dockerfile . --tag "ghcr.io/wemem/omnivore-content-fetch:${GITHUB_SHA}" --tag ghcr.io/wemem/omnivore-content-fetch:latest
          docker push ghcr.io/wemem/omnivore-content-fetch:${GITHUB_SHA}
